// =============================================================
// Rosters Blood Bowl 2025 (Third Season Edition) - VERSION FR
// Source : Livre de règles officiel français BB2025
// =============================================================
// 28 races officielles - vérifiées depuis le livre FR
// Catégories de skills (FR) :
//   G = Général       A = Agilité (Esquive)
//   S = Force         P = Passe
//   M = Mutation      F = Frappe (Devious/Fourbe)
// =============================================================

const ROSTERS = {

  // ============== ALLIANCE DU VIEUX MONDE ==============
  alliance_vieux_monde: {
    name: 'Alliance du Vieux Monde',
    edition: 'BB2025',
    tier: 2,
    rerollCost: 70,
    apothecary: true,
    league: ['Classique du Vieux Monde'],
    specialRules: [],
    bigGuyGroupLimit: 1,
    positions: [
      {
        title: 'Trois-Quart Humain',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 50,
        ma: 6, st: 3, ag: 3, pa: 4, av: 9,
        skills: [],
        normal: ['G'], double: ['A','F'],
      },
      {
        title: 'Aspirant Halfling',
        sub: 'Halfling, Trois-Quart',
        max: 5, cost: 30,
        ma: 5, st: 2, ag: 3, pa: 4, av: 7,
        skills: ['Esquive','Poids Plume','Minus'],
        normal: ['A'], double: ['G','F'],
      },
      {
        title: 'Receveur Humain',
        sub: 'Humain, Receveur',
        max: 1, cost: 75,
        ma: 8, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Réception','Esquive'],
        normal: ['A','G'], double: ['P','F'],
      },
      {
        title: 'Trois-Quart Nain',
        sub: 'Nain, Trois-Quart',
        max: 3, cost: 70,
        ma: 4, st: 3, ag: 4, pa: 5, av: 10,
        skills: ['Blocage','Défenseur','Crâne Épais'],
        normal: ['S','G'], double: ['F'],
      },
      {
        title: 'Lanceur Humain',
        sub: 'Humain, Lanceur',
        max: 1, cost: 75,
        ma: 6, st: 3, ag: 3, pa: 3, av: 9,
        skills: ['Passe','Prise Sûre'],
        normal: ['G','P'], double: ['A','F'],
      },
      {
        title: 'Coureur Nain',
        sub: 'Nain, Coureur',
        max: 1, cost: 80,
        ma: 6, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Sprint','Prise Sûre','Crâne Épais'],
        normal: ['G','P'], double: ['A','F'],
      },
      {
        title: 'Blitzer Humain',
        sub: 'Humain, Blitzer',
        max: 1, cost: 85,
        ma: 7, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Blocage','Tacle'],
        normal: ['G','F'], double: ['A'],
      },
      {
        title: 'Blitzer Nain',
        sub: 'Nain, Blitzer',
        max: 1, cost: 100,
        ma: 5, st: 3, ag: 4, pa: 4, av: 10,
        skills: ['Blocage','Tacle Plongeant','Tacle','Crâne Épais'],
        normal: ['G','F'], double: ['P'],
      },
      {
        title: 'Tueur de Trolls',
        sub: 'Nain, Spécial',
        max: 1, cost: 95,
        ma: 5, st: 3, ag: 4, pa: 5, av: 9,
        skills: ['Blocage','Intrépide','Frénésie','Haine (Troll)','Crâne Épais'],
        normal: ['G','F'], double: ['A'],
      },
      {
        title: 'Ogre',
        sub: 'Ogre, Gros Bras',
        max: 1, cost: 140,
	inBigGuyGroup: true,
        ma: 5, st: 5, ag: 4, pa: 5, av: 10,
        skills: ['Cerveau Lent','Châtaigne','Solitaire (3+)','Crâne Épais','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','M'],
      },
      {
        title: 'Homme-arbre de l\'Altern',
        sub: 'Homme-arbre, Gros Bras',
        max: 1, cost: 120,
	inBigGuyGroup: true,
        ma: 2, st: 6, ag: 5, pa: 5, av: 11,
        skills: ['Châtaigne','Stabilité','Bras Musclé','Prendre Racine','Crâne Épais','Lancer de Coéquipier','Timmm-ber!'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

  // ============== AMAZONES ==============
  amazones: {
    name: 'Amazones',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: true,
    league: ['Super-Ligue de Lustrie'],
    specialRules: [],
    positions: [
      {
        title: 'Guerrière Aigle',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 50,
        ma: 6, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Esquive'],
        normal: ['G'], double: ['A','F'],
      },
      {
        title: 'Guerrière Python',
        sub: 'Humain, Lanceur',
        max: 2, cost: 80,
        ma: 6, st: 3, ag: 3, pa: 3, av: 8,
        skills: ['Esquive','Sur le Ballon','Passe','Passe Assurée'],
        normal: ['G','P'], double: ['A','F'],
      },
      {
        title: 'Guerrière Piranha',
        sub: 'Humain, Blitzer',
        max: 2, cost: 90,
        ma: 7, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Esquive','Frappe-et-court','Rétablissement'],
        normal: ['A','G'], double: ['F'],
      },
      {
        title: 'Guerrière Jaguar',
        sub: 'Humain, Bloqueur',
        max: 2, cost: 110,
        ma: 6, st: 4, ag: 3, pa: 4, av: 9,
        skills: ['Défenseur','Esquive'],
        normal: ['G','F'], double: ['A'],
      },
    ],
  },

  // ============== BAS-FONDS ==============
  bas_fonds: {
    name: 'Bas-fonds',
    edition: 'BB2025',
    tier: 2,
    rerollCost: 70,
    apothecary: true,
    league: ['Défi des Bas-Fonds'],
    specialRules: ['Chantage et Corruption'],
    bigGuyGroupLimit: 1,
    positions: [
      {
        title: 'Trois-Quart Gobelin',
        sub: 'Gobelin, Trois-Quart',
        max: 16, cost: 40,
        ma: 6, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Esquive','Poids Plume','Minus'],
        normal: ['A','S','M'], double: ['G','P','F'],
      },
      {
        title: 'Trois-Quart Snotling',
        sub: 'Snotling, Trois-Quart',
        max: 6, cost: 15,
        ma: 5, st: 1, ag: 3, pa: 4, av: 6,
        skills: ['Esquive','Insignifiant','Poids Plume','Glissade Contrôlée','Minus','Microbe'],
        normal: ['A','S','M'], double: ['G'],
      },
      {
        title: 'Rat des Clans Skaven',
        sub: 'Skaven, Trois-Quart',
        max: 3, cost: 50,
        ma: 7, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Animosité (Gobelins)'],
        normal: ['S','G','M'], double: ['A','F'],
      },
      {
        title: 'Lanceur Skaven',
        sub: 'Skaven, Lanceur',
        max: 1, cost: 80,
        ma: 7, st: 3, ag: 3, pa: 2, av: 8,
        skills: ['Animosité (Gobelins)','Passe','Prise Sûre'],
        normal: ['G','M','P'], double: ['A','S','F'],
      },
      {
        title: 'Coureur d\'Égouts',
        sub: 'Skaven, Coureur',
        max: 1, cost: 85,
        ma: 9, st: 2, ag: 2, pa: 4, av: 8,
        skills: ['Animosité (Gobelins)','Esquive','Poignard'],
        normal: ['A','S','G','M'], double: ['F'],
      },
      {
        title: 'Blitzer Skaven',
        sub: 'Skaven, Blitzer',
        max: 1, cost: 90,
        ma: 8, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Animosité (Gobelins)','Blocage','Arracher le Ballon'],
        normal: ['G','M','F'], double: ['A','S'],
      },
      {
        title: 'Troll',
        sub: 'Troll, Gros Bras',
        max: 1, cost: 115,
	inBigGuyGroup: true,
        ma: 4, st: 5, ag: 5, pa: 5, av: 10,
        skills: ['Toujours Affamé','Solitaire (4+)','Châtaigne','Gerbe de Vomi','Gros Débile','Régénération','Lancer de Coéquipier'],
        normal: ['M','F'], double: ['A','G','P'],
      },
      {
        title: 'Rat-ogre',
        sub: 'Skaven, Gros Bras',
        max: 1, cost: 150,
	inBigGuyGroup: true,
        ma: 6, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Sauvagerie Animale','Frénésie','Solitaire (4+)','Châtaigne','Queue Préhensile'],
        normal: ['M','F'], double: ['A','G'],
      },
    ],
  },

  // ============== BRETONNIENS ==============
  bretonniens: {
    name: 'Bretonniens',
    edition: 'BB2025',
    tier: 2,
    rerollCost: 60,
    apothecary: true,
    league: ['Classique du Vieux Monde'],
    specialRules: [],
    positions: [
      {
        title: 'Écuyer Bretonnien',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 50,
        ma: 6, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Lutte'],
        normal: ['G'], double: ['A','F'],
      },
      {
        title: 'Receveur Chevalier Bretonnien',
        sub: 'Humain, Receveur',
        max: 2, cost: 85,
        ma: 7, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Réception','Intrépide','Nerfs d\'Acier'],
        normal: ['A','G'], double: ['F'],
      },
      {
        title: 'Lanceur Chevalier Bretonnien',
        sub: 'Humain, Lanceur',
        max: 2, cost: 80,
        ma: 6, st: 3, ag: 3, pa: 3, av: 9,
        skills: ['Intrépide','Nerfs d\'Acier','Passe'],
        normal: ['G','P'], double: ['A','F'],
      },
      {
        title: 'Chevalier du Graal',
        sub: 'Humain, Blitzer',
        max: 2, cost: 95,
        ma: 7, st: 3, ag: 3, pa: 4, av: 10,
        skills: ['Blocage','Intrépide','Appuis Sûrs'],
        normal: ['G','F'], double: ['A'],
      },
    ],
  },

  // ============== ELFES NOIRS ==============
  elfes_noirs: {
    name: 'Elfes Noirs',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 50,
    apothecary: true,
    league: ['Ligue des Royaumes Elfiques'],
    specialRules: [],
    positions: [
      {
        title: 'Trois-Quart Elfe Noir',
        sub: 'Elfe, Trois-Quart',
        max: 16, cost: 65,
        ma: 6, st: 3, ag: 2, pa: 3, av: 9,
        skills: [],
        normal: ['A','G'], double: ['S','F'],
      },
      {
        title: 'Coureur Elfe Noir',
        sub: 'Elfe, Coureur',
        max: 2, cost: 80,
        ma: 7, st: 3, ag: 2, pa: 3, av: 8,
        skills: ['Délestage','Dégagement'],
        normal: ['A','G','P'], double: ['S','F'],
      },
      {
        title: 'Assassin Elfe Noir',
        sub: 'Elfe, Spécial',
        max: 2, cost: 90,
        ma: 7, st: 3, ag: 2, pa: 4, av: 8,
        skills: ['Frappe-et-court','Poursuite','Poignard'],
        normal: ['A','S'], double: ['G','F'],
      },
      {
        title: 'Blitzer Elfe Noir',
        sub: 'Elfe, Blitzer',
        max: 2, cost: 105,
        ma: 7, st: 3, ag: 2, pa: 3, av: 9,
        skills: ['Blocage'],
        normal: ['A','G'], double: ['S','P','F'],
      },
      {
        title: 'Furie Elfe Noire',
        sub: 'Elfe, Spécial',
        max: 2, cost: 110,
        ma: 7, st: 3, ag: 2, pa: 4, av: 8,
        skills: ['Esquive','Frénésie','Rétablissement'],
        normal: ['A','G'], double: ['S','F'],
      },
    ],
  },

  // ============== ELFES SYLVAINS ==============
  elfes_sylvains: {
    name: 'Elfes Sylvains',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 50,
    apothecary: true,
    league: ['Ligue des Royaumes Elfiques', 'Ligue Sylvestre'],
    specialRules: [],
    positions: [
      {
        title: 'Trois-Quart Elfe Sylvain',
        sub: 'Elfe, Trois-Quart',
        max: 16, cost: 65,
        ma: 7, st: 3, ag: 2, pa: 3, av: 8,
        skills: [],
        normal: ['A','G'], double: ['F'],
      },
      {
        title: 'Lanceur Elfe Sylvain',
        sub: 'Elfe, Lanceur',
        max: 2, cost: 85,
        ma: 7, st: 3, ag: 2, pa: 2, av: 8,
        skills: ['Passe','Libération Contrôlée'],
        normal: ['A','G','P'], double: ['F'],
      },
      {
        title: 'Receveur Elfe Sylvain',
        sub: 'Elfe, Receveur',
        max: 2, cost: 90,
        ma: 8, st: 2, ag: 2, pa: 3, av: 8,
        skills: ['Réception','Esquive','Sprint'],
        normal: ['A','G'], double: ['P','F'],
      },
      {
        title: 'Danseur de Guerre',
        sub: 'Elfe, Blitzer',
        max: 2, cost: 130,
        ma: 8, st: 3, ag: 2, pa: 3, av: 8,
        skills: ['Blocage','Esquive','Saut'],
        normal: ['A','G'], double: ['P','F'],
      },
      {
        title: 'Homme-arbre de la Loren',
        sub: 'Homme-arbre, Gros Bras',
        max: 1, cost: 120,
        ma: 2, st: 6, ag: 5, pa: 5, av: 11,
        skills: ['Solitaire (4+)','Châtaigne','Stabilité','Bras Musclé','Prendre Racine','Crâne Épais','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

  // ============== ÉLUS DU CHAOS ==============
  elus_chaos: {
    name: 'Élus du Chaos',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 50,
    apothecary: true,
    league: ['Clash du Chaos'],
    specialRules: ['Favoris de (au choix)'],
    bigGuyGroupLimit: 1,
  positions: [
      {
        title: 'Trois-Quart Homme-bête',
        sub: 'Homme-bête, Trois-Quart',
        max: 16, cost: 55,
        ma: 6, st: 3, ag: 3, pa: 3, av: 9,
        skills: ['Cornes','Crâne Épais'],
        normal: ['G','M'], double: ['A','S','P','F'],
      },
      {
        title: 'Élu du Chaos',
        sub: 'Humain, Bloqueur',
        max: 4, cost: 100,
        ma: 5, st: 4, ag: 3, pa: 5, av: 10,
        skills: ['Clé de Bras'],
        normal: ['G','M','F'], double: ['A','S'],
      },
      {
        title: 'Troll',
        sub: 'Troll, Gros Bras',
        max: 1, cost: 115,
	inBigGuyGroup: true,
        ma: 4, st: 5, ag: 5, pa: 5, av: 10,
        skills: ['Toujours Affamé','Solitaire (4+)','Châtaigne','Gerbe de Vomi','Gros Débile','Régénération','Lancer de Coéquipier'],
        normal: ['M','F'], double: ['A','G','P'],
      },
      {
        title: 'Ogre',
        sub: 'Ogre, Gros Bras',
        max: 1, cost: 140,
	inBigGuyGroup: true,
        ma: 5, st: 5, ag: 4, pa: 5, av: 10,
        skills: ['Cerveau Lent','Solitaire (4+)','Châtaigne','Crâne Épais','Lancer de Coéquipier'],
        normal: ['M','F'], double: ['A','G'],
      },
      {
        title: 'Minotaure',
        sub: 'Minotaure, Gros Bras',
        max: 1, cost: 150,
	inBigGuyGroup: true,
        ma: 5, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Frénésie','Cornes','Solitaire (4+)','Châtaigne','Crâne Épais','Fureur Débridée'],
        normal: ['M','F'], double: ['A','G'],
      },
    ],
  },

  // ============== GNOMES ==============
  gnomes: {
    name: 'Gnomes',
    edition: 'BB2025',
    tier: 2,
    rerollCost: 50,
    apothecary: true,
    league: ['Coupe Dé à Coudre Halfling', 'Ligue Sylvestre'],
    specialRules: [],
    positions: [
      {
        title: 'Trois-Quart Gnome',
        sub: 'Gnome, Trois-Quart',
        max: 16, cost: 40,
        ma: 5, st: 2, ag: 3, pa: 4, av: 7,
        skills: ['Rétablissement','Poids Plume','Minus','Lutte'],
        normal: ['A'], double: ['S','G','F'],
      },
      {
        title: 'Renard Sylvestre',
        sub: 'Animal, Coureur',
        max: 2, cost: 50,
        ma: 7, st: 2, ag: 2, pa: '-', av: 6,
        skills: ['Esquive','Mon Ballon','Glissade Contrôlée','Minus'],
        normal: [], double: ['A'],
      },
      {
        title: 'Illusionniste Gnome',
        sub: 'Gnome, Spécial',
        max: 2, cost: 50,
        ma: 5, st: 2, ag: 3, pa: 3, av: 7,
        skills: ['Rétablissement','Minus','Farceur','Lutte'],
        normal: ['A','P'], double: ['S','G'],
      },
      {
        title: 'Belluaire Gnome',
        sub: 'Gnome, Bloqueur',
        max: 2, cost: 55,
        ma: 5, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Garde','Rétablissement','Minus','Lutte'],
        normal: ['A'], double: ['S','G','F'],
      },
      {
        title: 'Homme-arbre de l\'Altern',
        sub: 'Homme-arbre, Gros Bras',
        max: 2, cost: 120,
        ma: 2, st: 6, ag: 5, pa: 5, av: 11,
        skills: ['Châtaigne','Stabilité','Bras Musclé','Prendre Racine','Crâne Épais','Lancer de Coéquipier','Timmm-ber!'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

  // ============== GOBELINS ==============
  gobelins: {
    name: 'Gobelins',
    edition: 'BB2025',
    tier: 3,
    rerollCost: 60,
    apothecary: true,
    league: ['Bagarre des Terres Arides', 'Défi des Bas-Fonds'],
    specialRules: ['Chantage et Corruption'],
    positions: [
      {
        title: 'Trois-Quart Gobelin',
        sub: 'Gobelin, Trois-Quart',
        max: 16, cost: 40,
        ma: 6, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Esquive','Poids Plume','Minus'],
        normal: ['A','S'], double: ['G','P','F'],
      },
      {
        title: 'Cinglé',
        sub: 'Gobelin, Spécial',
        max: 1, cost: 40,
        ma: 6, st: 2, ag: 3, pa: '-', av: 8,
        skills: ['Tronçonneuse','Minus','Sans Ballon','Arme Secrète'],
        normal: ['S'], double: ['A','G','F'],
      },
      {
        title: 'Bomba',
        sub: 'Gobelin, Spécial',
        max: 1, cost: 45,
        ma: 6, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Bombardier','Esquive','Arme Secrète','Minus'],
        normal: ['S','P'], double: ['A','G','F'],
      },
      {
        title: 'Ouligan\'',
        sub: 'Gobelin, Spécial',
        max: 1, cost: 60,
        ma: 6, st: 2, ag: 3, pa: 5, av: 8,
        skills: ['Joueur Déloyal','Présence Perturbante','Esquive','Poids Plume','Minus','Provocation'],
        normal: ['A','S'], double: ['G','F'],
      },
      {
        title: 'Plongeur de la Mort',
        sub: 'Gobelin, Spécial',
        max: 1, cost: 65,
        ma: 6, st: 2, ag: 3, pa: 6, av: 8,
        skills: ['Esquive','Poids Plume','Minus','Piqué'],
        normal: ['A'], double: ['S','G','F'],
      },
      {
        title: 'Fanatique',
        sub: 'Gobelin, Spécial',
        max: 1, cost: 70,
        ma: 3, st: 7, ag: 3, pa: '-', av: 8,
        skills: ['Chaîne et Boulet','Minus','Sans Ballon','Arme Secrète'],
        normal: ['S','F'], double: ['A','G'],
      },
      {
        title: 'Échassier à Ressort',
        sub: 'Gobelin, Spécial',
        max: 1, cost: 75,
        ma: 7, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Esquive','Minus','Monté sur Ressort'],
        normal: ['A'], double: ['S','G','F'],
      },
      {
        title: 'Troll Entraîné',
        sub: 'Troll, Gros Bras',
        max: 2, cost: 115,
        ma: 4, st: 5, ag: 5, pa: 5, av: 10,
        skills: ['Toujours Affamé','Châtaigne','Gros Débile','Gerbe de Vomi','Régénération','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

  // ============== HALFLINGS ==============
  halflings: {
    name: 'Halflings',
    edition: 'BB2025',
    tier: 3,
    rerollCost: 60,
    apothecary: true,
    league: ['Coupe Dé à Coudre Halfling', 'Ligue Sylvestre'],
    specialRules: [],
    positions: [
      {
        title: 'Aspirant Halfling',
        sub: 'Halfling, Trois-Quart',
        max: 16, cost: 30,
        ma: 5, st: 2, ag: 3, pa: 4, av: 7,
        skills: ['Esquive','Poids Plume','Minus'],
        normal: ['A'], double: ['S','G','F'],
      },
      {
        title: 'Balaise Halfling',
        sub: 'Halfling, Bloqueur',
        max: 2, cost: 50,
        ma: 5, st: 2, ag: 3, pa: 3, av: 8,
        skills: ['Esquive','Parade','Minus'],
        normal: ['A','P'], double: ['S','G','F'],
      },
      {
        title: 'Receveur Halfling',
        sub: 'Halfling, Receveur',
        max: 2, cost: 55,
        ma: 5, st: 2, ag: 3, pa: 4, av: 7,
        skills: ['Réception','Esquive','Poids Plume','Sprint','Minus'],
        normal: ['A'], double: ['S','G','F'],
      },
      {
        title: 'Homme-arbre de l\'Altern',
        sub: 'Homme-arbre, Gros Bras',
        max: 2, cost: 120,
        ma: 2, st: 6, ag: 5, pa: 5, av: 11,
        skills: ['Châtaigne','Stabilité','Bras Musclé','Prendre Racine','Crâne Épais','Lancer de Coéquipier','Timmm-ber!'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

// ============== HAUTS ELFES ==============
  hauts_elfes: {
    name: 'Hauts Elfes',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 50,
    apothecary: true,
    league: ['Ligue des Royaumes Elfiques'],
    specialRules: [],
    positions: [
      {
        title: 'Trois-Quart Haut Elfe',
        sub: 'Elfe, Trois-Quart',
        max: 16, cost: 65,
        ma: 6, st: 3, ag: 2, pa: 3, av: 9,
        skills: [],
        normal: ['A','G'], double: ['F'],
      },
      {
        title: 'Guerrier Phoenix',
        sub: 'Elfe, Lanceur',
        max: 2, cost: 90,
        ma: 6, st: 3, ag: 2, pa: 2, av: 9,
        skills: ['Perce-nuages','Passe','Passe Assurée'],
        normal: ['A','G','P'], double: ['F'],
      },
      {
        title: 'Prince Dragon',
        sub: 'Elfe, Receveur',
        max: 4, cost: 110,
        ma: 8, st: 3, ag: 2, pa: 4, av: 9,
        skills: ['Appuis sûrs', 'Blocage', 'Ma Balle'],
        normal: ['A','G'], double: ['F'],
      },
      {
        title: 'Lion Blanc Haut Elfe',
        sub: 'Elfe, Blitzer',
        max: 2, cost: 110,
        ma: 7, st: 3, ag: 2, pa: 3, av: 9,
        skills: ['Griffes', 'Lutte'],
        normal: ['A','G'], double: ['P','F'],
      },
    ],
  },

  // ============== HOMMES-LÉZARDS ==============
  hommes_lezards: {
    name: 'Hommes-Lézards',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 70,
    apothecary: true,
    league: ['Super-Ligue de Lustrie'],
    specialRules: [],
    positions: [
      {
        title: 'Trois-Quart Skink',
        sub: 'Homme-lézard, Trois-Quart',
        max: 16, cost: 60,
        ma: 8, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Esquive','Minus'],
        normal: ['A'], double: ['G','S','P','F'],
      },
      {
        title: 'Skink Caméléon',
        sub: 'Homme-lézard, Lanceur',
        max: 2, cost: 70,
        ma: 7, st: 2, ag: 3, pa: 3, av: 8,
        skills: ['Esquive','Sur le Ballon','Poursuite','Minus'],
        normal: ['A','P'], double: ['G','S','F'],
      },
      {
        title: 'Bloqueur Saurus',
        sub: 'Homme-lézard, Bloqueur',
        max: 6, cost: 90,
        ma: 6, st: 4, ag: 5, pa: 6, av: 10,
        skills: ['Juggernaut','Instable'],
        normal: ['G','F'], double: ['A'],
      },
      {
        title: 'Kroxigor',
        sub: 'Homme-lézard, Gros Bras',
        max: 1, cost: 140,
        ma: 6, st: 5, ag: 5, pa: 6, av: 10,
        skills: ['Cerveau Lent','Solitaire (4+)','Châtaigne','Queue Préhensile','Crâne Épais'],
        normal: ['F'], double: ['A','G'],
      },
    ],
  },

  // ============== HORREURS NÉCROMANTIQUES ==============
  horreurs_necromantiques: {
    name: 'Horreurs Nécromantiques',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 70,
    apothecary: false,
    league: ['Spot de Sylvanie'],
    specialRules: ['Maîtres de la Non-vie'],
    positions: [
      {
        title: 'Trois-Quart Zombie',
        sub: 'Humain, Trois-Quart, Mort-vivant, Zombie',
        max: 16, cost: 40,
        ma: 4, st: 3, ag: 4, pa: 6, av: 9,
        skills: ['Fourchette','Régénération','Instable'],
        normal: ['S','G'], double: ['A','F'],
      },
      {
        title: 'Coureur Goule',
        sub: 'Goule, Coureur, Mort-vivant',
        max: 2, cost: 75,
        ma: 7, st: 3, ag: 3, pa: 3, av: 8,
        skills: ['Esquive','Régénération'],
        normal: ['A','G'], double: ['S','P','F'],
      },
      {
        title: 'Spectre',
        sub: 'Spectre, Bloqueur, Mort-vivant',
        max: 2, cost: 85,
        ma: 6, st: 3, ag: 3, pa: '-', av: 9,
        skills: ['Blocage','Répulsion','Sans Ballon','Glissade Contrôlée','Régénération'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Golem de Chair',
        sub: 'Amalgame, Bloqueur, Mort-vivant',
        max: 2, cost: 110,
        ma: 4, st: 4, ag: 4, pa: 6, av: 10,
        skills: ['Régénération','Stabilité','Crâne Épais','Instable'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Loup-garou',
        sub: 'Loup-garou, Blitzer, Mort-vivant',
        max: 2, cost: 120,
        ma: 8, st: 3, ag: 3, pa: 3, av: 9,
        skills: ['Griffes','Frénésie','Régénération'],
        normal: ['A','G'], double: ['S','P','F'],
      },
    ],
  },

  // ============== HUMAINS ==============
  humains: {
    name: 'Humains',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 50,
    apothecary: true,
    league: ['Classique du Vieux Monde'],
    specialRules: ['Capitaine'],
    positions: [
      {
        title: 'Trois-Quart Humain',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 50,
        ma: 6, st: 3, ag: 3, pa: 4, av: 9,
        skills: [],
        normal: ['G'], double: ['A','S','F'],
      },
      {
        title: 'Aspirant Halfling',
        sub: 'Halfling, Trois-Quart',
        max: 3, cost: 30,
        ma: 5, st: 2, ag: 3, pa: 4, av: 7,
        skills: ['Esquive','Poids Plume','Minus'],
        normal: ['A'], double: ['S','G','F'],
      },
      {
        title: 'Receveur Humain',
        sub: 'Humain, Receveur',
        max: 2, cost: 75,
        ma: 8, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Réception','Esquive'],
        normal: ['A','G'], double: ['S','P','F'],
      },
      {
        title: 'Lanceur Humain',
        sub: 'Humain, Lanceur',
        max: 2, cost: 75,
        ma: 6, st: 3, ag: 3, pa: 3, av: 9,
        skills: ['Passe','Prise Sûre'],
        normal: ['G','P'], double: ['A','S','F'],
      },
      {
        title: 'Blitzer Humain',
        sub: 'Humain, Blitzer',
        max: 2, cost: 85,
        ma: 7, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Blocage','Tacle'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Ogre',
        sub: 'Ogre, Gros Bras',
        max: 1, cost: 140,
        ma: 5, st: 5, ag: 4, pa: 5, av: 10,
        skills: ['Cerveau Lent','Solitaire (3+)','Châtaigne','Crâne Épais','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','M'],
      },
    ],
  },

  // ============== KHORNE ==============
  khorne: {
    name: 'Khorne',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: true,
    league: ['Clash du Chaos'],
    specialRules: ['Bagarreurs Brutaux','Favoris de Khorne'],
    positions: [
      {
        title: 'Maraudeur Sanglant',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 50,
        ma: 6, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Frénésie'],
        normal: ['G','M'], double: ['A','S','F'],
      },
      {
        title: 'Khorngor',
        sub: 'Homme-bête, Coureur',
        max: 2, cost: 70,
        ma: 6, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Cornes','Juggernaut','Rétablissement','Crâne Épais'],
        normal: ['G','M','F'], double: ['A','S','P'],
      },
      {
        title: 'Rabatteur Sanglant',
        sub: 'Humain, Bloqueur',
        max: 4, cost: 105,
        ma: 5, st: 4, ag: 4, pa: 6, av: 10,
        skills: ['Frénésie'],
        normal: ['G','M','F'], double: ['A','S'],
      },
      {
        title: 'Rejeton Sanglant',
        sub: 'Rejeton, Gros Bras',
        max: 1, cost: 160,
        ma: 5, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Griffes','Frénésie','Solitaire (4+)','Châtaigne','Fureur Débridée'],
        normal: ['M','F'], double: ['A','G'],
      },
    ],
  },

  // ============== MORTS AMBULANTS ==============
  morts_ambulants: {
    name: 'Morts Ambulants',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 70,
    apothecary: false,
    league: ['Spot de Sylvanie'],
    specialRules: ['Maîtres de la Non-vie'],
    positions: [
      {
        title: 'Trois-Quart Squelette',
        sub: 'Humain, Mort-vivant, Squelette, Trois-Quart',
        max: 16, cost: 40,
        ma: 5, st: 3, ag: 4, pa: 6, av: 8,
        skills: ['Régénération','Crâne Épais'],
        normal: ['G'], double: ['A','S','F'],
      },
      {
        title: 'Trois-Quart Zombie',
        sub: 'Humain, Trois-Quart, Zombie, Mort-vivant',
        max: 16, cost: 40,
        ma: 4, st: 3, ag: 4, pa: 6, av: 9,
        skills: ['Fourchette','Régénération','Instable'],
        normal: ['S','G'], double: ['A','F'],
      },
      {
        title: 'Coureur Goule',
        sub: 'Goule, Coureur, Mort-vivant',
        max: 2, cost: 75,
        ma: 7, st: 3, ag: 3, pa: 3, av: 8,
        skills: ['Esquive','Régénération'],
        normal: ['A','G'], double: ['S','P','F'],
      },
      {
        title: 'Blitzer Revenant',
        sub: 'Humain, Squelette, Blitzer, Mort-vivant',
        max: 2, cost: 95,
        ma: 6, st: 3, ag: 3, pa: 5, av: 9,
        skills: ['Blocage','Régénération','Tacle','Crâne Épais'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Momie',
        sub: 'Humain, Mort-vivant, Bloqueur, Gros Bras',
        max: 2, cost: 125,
        ma: 3, st: 5, ag: 5, pa: 6, av: 10,
        skills: ['Châtaigne','Régénération'],
        normal: ['F'], double: ['A','G'],
      },
    ],
  },

  // ============== NAINS ==============
  nains: {
    name: 'Nains',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: true,
    league: ['Super-Ligue du Bord du Monde'],
    specialRules: ['Bagarreurs Brutaux','Chantage et Corruption'],
    positions: [
      {
        title: 'Trois-Quart Nain',
        sub: 'Nain, Trois-Quart',
        max: 16, cost: 70,
        ma: 4, st: 3, ag: 4, pa: 5, av: 10,
        skills: ['Blocage','Défenseur','Crâne Épais'],
        normal: ['S','G'], double: ['F'],
      },
      {
        title: 'Coureur Nain',
        sub: 'Nain, Coureur',
        max: 2, cost: 80,
        ma: 6, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Sprint','Prise Sûre','Crâne Épais'],
        normal: ['G','P'], double: ['F'],
      },
      {
        title: 'Blitzer Nain',
        sub: 'Nain, Blitzer',
        max: 2, cost: 100,
        ma: 5, st: 3, ag: 4, pa: 4, av: 10,
        skills: ['Blocage','Tacle Plongeant','Tacle','Crâne Épais'],
        normal: ['G','F'], double: ['P'],
      },
      {
        title: 'Tueur de Trolls',
        sub: 'Nain, Spécial',
        max: 2, cost: 95,
        ma: 5, st: 3, ag: 4, pa: 5, av: 9,
        skills: ['Blocage','Intrépide','Frénésie','Haine (Troll)','Crâne Épais'],
        normal: ['G','F'], double: ['S'],
      },
      {
        title: 'Roule-mort',
        sub: 'Nain, Gros Bras, Spécial',
        max: 1, cost: 170,
        ma: 5, st: 7, ag: 5, pa: '-', av: 11,
        skills: ['Esquive en Force','Joueur Déloyal','Juggernaut','Solitaire (4+)','Châtaigne','Sans Ballon','Stabilité','Arme Secrète'],
        normal: ['S','F'], double: ['G'],
      },
    ],
  },

  // ============== NAINS DU CHAOS ==============
  nains_chaos: {
    name: 'Nains du Chaos',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 70,
    apothecary: true,
    league: ['Bagarre des Terres Arides', 'Clash du Chaos'],
    specialRules: ['Favoris de Hashut'],
    positions: [
      {
        title: 'Trois-Quart Hobgobelin',
        sub: 'Gobelin, Trois-Quart',
        max: 16, cost: 40,
        ma: 6, st: 3, ag: 3, pa: 4, av: 8,
        skills: [],
        normal: ['S'], double: ['A','G','F'],
      },
      {
        title: 'Surineur Sournois',
        sub: 'Gobelin, Spécial',
        max: 2, cost: 60,
        ma: 6, st: 3, ag: 3, pa: 5, av: 8,
        skills: ['Poursuite','Poignard'],
        normal: ['S','G'], double: ['A','F'],
      },
      {
        title: 'Bloqueur Nain du Chaos',
        sub: 'Nain, Bloqueur',
        max: 4, cost: 70,
        ma: 4, st: 3, ag: 4, pa: 6, av: 10,
        skills: ['Blocage','Peau de Fer','Crâne Épais'],
        normal: ['G','F'], double: ['A','S','M'],
      },
      {
        title: 'Forgeflamme',
        sub: 'Nain, Spécial',
        max: 2, cost: 80,
        ma: 5, st: 3, ag: 4, pa: 6, av: 10,
        skills: ['Bagarreur','Souffle Ardent','Présence Perturbante','Crâne Épais'],
        normal: ['G','F'], double: ['A','S','M'],
      },
      {
        title: 'Centaure-taureau',
        sub: 'Nain, Blitzer',
        max: 2, cost: 130,
        ma: 6, st: 4, ag: 4, pa: 6, av: 10,
        skills: ['Sprint','Équilibre','Crâne Épais','Instable'],
        normal: ['G','F'], double: ['A','S','M'],
      },
      {
        title: 'Minotaure',
        sub: 'Minotaure, Gros Bras',
        max: 1, cost: 150,
        ma: 5, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Frénésie','Cornes','Solitaire (4+)','Châtaigne','Crâne Épais','Fureur Débridée'],
        normal: ['M','F'], double: ['A','G'],
      },
    ],
  },

  // ============== NOBLESSE IMPÉRIALE ==============
  noblesse_imperiale: {
    name: 'Noblesse Impériale',
    edition: 'BB2025',
    tier: 2,
    rerollCost: 60,
    apothecary: true,
    league: ['Classique du Vieux Monde'],
    specialRules: [],
    positions: [
      {
        title: 'Valet Impérial',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 45,
        ma: 6, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Parade'],
        normal: ['G'], double: ['A','F'],
      },
      {
        title: 'Lanceur Impérial',
        sub: 'Humain, Lanceur',
        max: 2, cost: 75,
        ma: 6, st: 3, ag: 3, pa: 2, av: 9,
        skills: ['Transmission dans la Course','Passe','Pro'],
        normal: ['G','P'], double: ['A','F'],
      },
      {
        title: 'Garde du Corps',
        sub: 'Humain, Bloqueur',
        max: 4, cost: 85,
        ma: 5, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Stabilité','Lutte'],
        normal: ['G','F'], double: ['A'],
      },
      {
        title: 'Blitzer Noble',
        sub: 'Humain, Blitzer',
        max: 2, cost: 90,
        ma: 7, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Blocage','Réception','Pro'],
        normal: ['A','G'], double: ['P','F'],
      },
      {
        title: 'Ogre',
        sub: 'Ogre, Gros Bras',
        max: 1, cost: 140,
        ma: 5, st: 5, ag: 4, pa: 5, av: 10,
        skills: ['Cerveau Lent','Solitaire (3+)','Châtaigne','Crâne Épais','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','M'],
      },
    ],
  },

  // ============== NORDIQUES ==============
  nordiques: {
    name: 'Nordiques',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: true,
    league: ['Clash du Chaos', 'Classique du Vieux Monde'],
    specialRules: ['Si Clash du Chaos est choisi, l\'équipe gagne Favoris de Khorne'],
    positions: [
      {
        title: 'Pillard Nordique',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 50,
        ma: 6, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Blocage','Ivrogne','Crâne Épais','Instable'],
        normal: ['G'], double: ['A','P','F'],
      },
      {
        title: 'Sanglier de Secours',
        sub: 'Animal, Spécial',
        max: 2, cost: 20,
        ma: 5, st: 1, ag: 3, pa: '-', av: 6,
        skills: ['Esquive','Sans Ballon','Petit Remontant','Minus','Microbe'],
        normal: [], double: ['A'],
      },
      {
        title: 'Berserker Nordique',
        sub: 'Humain, Blitzer',
        max: 2, cost: 90,
        ma: 6, st: 3, ag: 3, pa: 5, av: 8,
        skills: ['Blocage','Frénésie','Rétablissement'],
        normal: ['G','F'], double: ['A','P'],
      },
      {
        title: 'Valkyrie',
        sub: 'Humain, Receveur, Lanceur',
        max: 2, cost: 95,
        ma: 7, st: 3, ag: 3, pa: 3, av: 8,
        skills: ['Réception','Intrépide','Passe','Arracher le Ballon'],
        normal: ['A','G','P'], double: ['F'],
      },
      {
        title: 'Ulfwerener',
        sub: 'Humain, Bloqueur',
        max: 2, cost: 105,
        ma: 6, st: 4, ag: 4, pa: 6, av: 9,
        skills: ['Frénésie','Instable'],
        normal: ['G','F'], double: ['A'],
      },
      {
        title: 'Yéti',
        sub: 'Yéti, Gros Bras',
        max: 1, cost: 140,
        ma: 5, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Griffes','Frénésie','Présence Perturbante','Solitaire (4+)','Fureur Débridée'],
        normal: ['F'], double: ['A','G'],
      },
    ],
  },

  // ============== NURGLE ==============
  nurgle: {
    name: 'Nurgle',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: false,
    league: ['Clash du Chaos'],
    specialRules: ['Bagarreurs Brutaux','Favoris de Nurgle'],
    positions: [
      {
        title: 'Trois-Quart Putrescent',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 40,
        ma: 5, st: 3, ag: 4, pa: 6, av: 9,
        skills: ['Décomposition','Contagieux'],
        normal: ['S','G','M'], double: ['A','F'],
      },
      {
        title: 'Pestigor',
        sub: 'Homme-bête, Coureur',
        max: 2, cost: 70,
        ma: 6, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Cornes','Contagieux','Régénération','Appuis Sûrs','Crâne Épais'],
        normal: ['G','M','F'], double: ['A','S','P'],
      },
      {
        title: 'Boursouflé',
        sub: 'Humain, Bloqueur',
        max: 4, cost: 110,
        ma: 4, st: 4, ag: 4, pa: 6, av: 10,
        skills: ['Présence Perturbante','Répulsion','Contagieux','Régénération','Stabilité','Instable'],
        normal: ['G','M','F'], double: ['A','S'],
      },
      {
        title: 'Rejeton Putride',
        sub: 'Rejeton, Gros Bras',
        max: 1, cost: 140,
        ma: 4, st: 5, ag: 5, pa: 6, av: 10,
        skills: ['Présence Perturbante','Répulsion','Solitaire (4+)','Châtaigne','Contagieux','Petit Remontant','Gros Débile','Régénération','Tentacules'],
        normal: ['F'], double: ['S','G','M'],
      },
    ],
  },

  // ============== OGRES ==============
  ogres: {
    name: 'Ogres',
    edition: 'BB2025',
    tier: 3,
    rerollCost: 70,
    apothecary: true,
    league: ['Bagarre des Terres Arides', 'Super-Ligue du Bord du Monde'],
    specialRules: ['Bagarreurs Brutaux','Trois-Quarts à Vil Prix'],
    positions: [
      {
        title: 'Trois-Quart Gnoblar',
        sub: 'Gnoblar, Trois-Quart',
        max: 16, cost: 15,
        ma: 5, st: 1, ag: 3, pa: 4, av: 6,
        skills: ['Esquive','Poids Plume','Glissade Contrôlée','Minus','Microbe'],
        normal: ['A','S'], double: ['G'],
      },
      {
        title: 'Bloqueur Ogre',
        sub: 'Ogre, Bloqueur, Gros Bras',
        max: 5, cost: 140,
        ma: 5, st: 5, ag: 4, pa: 5, av: 10,
        skills: ['Cerveau Lent','Châtaigne','Crâne Épais','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','S','G','P'],
      },
      {
        title: 'Botte-nabots Ogre',
        sub: 'Ogre, Lanceur, Gros Bras',
        max: 1, cost: 145,
        ma: 5, st: 5, ag: 4, pa: 4, av: 10,
        skills: ['Cerveau Lent','Botter de Coéquipier','Châtaigne','Crâne Épais'],
        normal: ['P','F'], double: ['A','S','G'],
      },
    ],
  },

  // ============== ORQUES ==============
  orques: {
    name: 'Orques',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: true,
    league: ['Bagarre des Terres Arides'],
    specialRules: ['Bagarreurs Brutaux','Capitaine'],
    positions: [
      {
        title: 'Trois-Quart Orque',
        sub: 'Orque, Trois-Quart',
        max: 16, cost: 50,
        ma: 5, st: 3, ag: 3, pa: 4, av: 10,
        skills: [],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Trois-Quart Gobelin',
        sub: 'Gobelin, Trois-Quart',
        max: 4, cost: 40,
        ma: 6, st: 2, ag: 3, pa: 3, av: 8,
        skills: ['Esquive','Poids Plume','Minus'],
        normal: ['A','S'], double: ['G','P','F'],
      },
      {
        title: 'Lanceur Orque',
        sub: 'Orque, Lanceur',
        max: 2, cost: 75,
        ma: 6, st: 3, ag: 3, pa: 3, av: 9,
        skills: ['Passe','Prise Sûre'],
        normal: ['G','P'], double: ['A','S','F'],
      },
      {
        title: 'Blitzer Orque',
        sub: 'Orque, Blitzer',
        max: 2, cost: 85,
        ma: 6, st: 3, ag: 3, pa: 4, av: 10,
        skills: ['Blocage','Esquive en Force'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Bloqueur Kosto',
        sub: 'Orque, Bloqueur',
        max: 2, cost: 95,
        ma: 5, st: 4, ag: 4, pa: 6, av: 10,
        skills: ['Châtaigne','Provocation','Crâne Épais','Instable'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Troll',
        sub: 'Troll, Gros Bras',
        max: 1, cost: 115,
        ma: 4, st: 5, ag: 5, pa: 5, av: 10,
        skills: ['Toujours Affamé','Solitaire (4+)','Châtaigne','Gerbe de Vomi','Gros Débile','Régénération','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

  // ============== ORQUES NOIRS ==============
  orques_noirs: {
    name: 'Orques Noirs',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: true,
    league: ['Bagarre des Terres Arides'],
    specialRules: ['Bagarreurs Brutaux','Chantage et Corruption'],
    positions: [
      {
        title: 'Malabar Gobelin',
        sub: 'Gobelin, Trois-Quart',
        max: 16, cost: 45,
        ma: 6, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Esquive','Poids Plume','Minus','Crâne Épais'],
        normal: ['A','S'], double: ['G','P','F'],
      },
      {
        title: 'Orque Noir',
        sub: 'Orque, Bloqueur',
        max: 6, cost: 90,
        ma: 4, st: 4, ag: 4, pa: 5, av: 10,
        skills: ['Bagarreur','Projection'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Troll Entraîné',
        sub: 'Troll, Gros Bras',
        max: 1, cost: 115,
        ma: 4, st: 5, ag: 5, pa: 5, av: 10,
        skills: ['Toujours Affamé','Châtaigne','Gerbe de Vomi','Gros Débile','Régénération','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

  // ============== RENÉGATS DU CHAOS ==============
  renegats_chaos: {
    name: 'Renégats du Chaos',
    edition: 'BB2025',
    tier: 2,
    rerollCost: 70,
    apothecary: true,
    league: ['Clash du Chaos'],
    specialRules: ['Favoris de (au choix : Khorne, Nurgle, Slaanesh, Tzeentch ou Chaos Universel)'],
    bigGuyGroupLimit: 3,
    positions: [
      {
        title: 'Humain Renégat',
        sub: 'Humain, Trois-Quart',
        max: 16, cost: 50,
        ma: 6, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Animosité (tous)'],
        normal: ['S','G','M'], double: ['A','F'],
      },
      {
        title: 'Gobelin Renégat',
        sub: 'Gobelin, Trois-Quart',
        max: 1, cost: 40,
        ma: 6, st: 2, ag: 3, pa: 4, av: 8,
        skills: ['Animosité (tous)','Esquive','Poids Plume','Minus'],
        normal: ['A','S','M'], double: ['G','P'],
      },
      {
        title: 'Orque Renégat',
        sub: 'Orque, Trois-Quart',
        max: 1, cost: 50,
        ma: 5, st: 3, ag: 3, pa: 4, av: 10,
        skills: ['Animosité (tous)'],
        normal: ['S','G','M'], double: ['A','F'],
      },
      {
        title: 'Skaven Renégat',
        sub: 'Skaven, Trois-Quart',
        max: 1, cost: 50,
        ma: 7, st: 3, ag: 3, pa: 4, av: 8,
        skills: ['Animosité (tous)'],
        normal: ['S','G','M'], double: ['A','F'],
      },
      {
        title: 'Elfe Noir Renégat',
        sub: 'Elfe, Trois-Quart',
        max: 1, cost: 65,
        ma: 6, st: 3, ag: 2, pa: 3, av: 9,
        skills: ['Animosité (tous)'],
        normal: ['A','S','G','M'], double: ['F'],
      },
      {
        title: 'Lanceur Humain Renégat',
        sub: 'Humain, Lanceur',
        max: 1, cost: 75,
        ma: 6, st: 3, ag: 3, pa: 3, av: 9,
        skills: ['Animosité (tous)','Passe','Prise Sûre'],
        normal: ['S','G','M','P'], double: ['A','F'],
      },
      {
        title: 'Troll',
        sub: 'Troll, Gros Bras',
        max: 1, cost: 115,
	inBigGuyGroup: true,
        ma: 4, st: 5, ag: 5, pa: 5, av: 10,
        skills: ['Toujours Affamé','Solitaire (4+)','Châtaigne','Gerbe de Vomi','Gros Débile','Régénération','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','M','P'],
      },
      {
        title: 'Ogre',
        sub: 'Ogre, Gros Bras',
        max: 1, cost: 140,
	inBigGuyGroup: true,
        ma: 5, st: 5, ag: 4, pa: 5, av: 10,
        skills: ['Cerveau Lent','Crâne Épais','Solitaire (4+)','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','M'],
      },
      {
        title: 'Minotaure',
        sub: 'Minotaure, Gros Bras',
        max: 1, cost: 150,
	inBigGuyGroup: true,
        ma: 5, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Frénésie','Cornes','Solitaire (4+)','Châtaigne','Crâne Épais','Fureur Débridée'],
        normal: ['F'], double: ['A','G','M'],
      },
      {
        title: 'Rat-ogre',
        sub: 'Skaven, Gros Bras',
        max: 1, cost: 150,
	inBigGuyGroup: true,
        ma: 6, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Sauvagerie Animale','Frénésie','Solitaire (4+)','Châtaigne','Queue Préhensile'],
        normal: ['F'], double: ['A','G','M'],
      },
    ],
  },

  // ============== ROIS DES TOMBES ==============
  rois_tombes: {
    name: 'Rois des Tombes',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 60,
    apothecary: false,
    league: ['Spot de Sylvanie'],
    specialRules: ['Maîtres de la Non-vie'],
    positions: [
      {
        title: 'Trois-Quart Squelette',
        sub: 'Humain, Squelette, Trois-Quart, Mort-vivant',
        max: 16, cost: 40,
        ma: 5, st: 3, ag: 4, pa: 6, av: 8,
        skills: ['Régénération','Crâne Épais'],
        normal: ['G'], double: ['A','S','F'],
      },
      {
        title: 'Lanceur des Rois des Tombes',
        sub: 'Humain, Squelette, Lanceur, Mort-vivant',
        max: 2, cost: 65,
        ma: 6, st: 3, ag: 4, pa: 3, av: 9,
        skills: ['Passe','Régénération','Prise Sûre','Crâne Épais'],
        normal: ['G','P'], double: ['A','S','F'],
      },
      {
        title: 'Blitzer des Rois des Tombes',
        sub: 'Humain, Squelette, Blitzer, Mort-vivant',
        max: 2, cost: 85,
        ma: 6, st: 3, ag: 4, pa: 5, av: 9,
        skills: ['Blocage','Régénération','Crâne Épais'],
        normal: ['G','F'], double: ['A','S'],
      },
      {
        title: 'Gardien des Tombes',
        sub: 'Humain, Gros Bras, Bloqueur, Mort-vivant',
        max: 4, cost: 115,
        ma: 4, st: 5, ag: 5, pa: 6, av: 10,
        skills: ['Bagarreur','Décomposition','Régénération'],
        normal: ['F'], double: ['A','G'],
      },
    ],
  },

  // ============== SKAVENS ==============
  skavens: {
    name: 'Skavens',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 50,
    apothecary: true,
    league: ['Défi des Bas-Fonds'],
    specialRules: [],
    positions: [
      {
        title: 'Rat des Clans Skaven',
        sub: 'Skaven, Trois-Quart',
        max: 16, cost: 50,
        ma: 7, st: 3, ag: 3, pa: 4, av: 8,
        skills: [],
        normal: ['S','G'], double: ['A','M','F'],
      },
      {
        title: 'Lanceur Skaven',
        sub: 'Skaven, Lanceur',
        max: 2, cost: 80,
        ma: 7, st: 3, ag: 3, pa: 2, av: 8,
        skills: ['Passe','Prise Sûre'],
        normal: ['G','P'], double: ['A','S','M','F'],
      },
      {
        title: 'Coureur d\'Égouts',
        sub: 'Skaven, Coureur',
        max: 2, cost: 85,
        ma: 9, st: 2, ag: 2, pa: 4, av: 8,
        skills: ['Esquive','Poignard'],
        normal: ['A','S','G'], double: ['M','F'],
      },
      {
        title: 'Blitzer Skaven',
        sub: 'Skaven, Blitzer',
        max: 2, cost: 90,
        ma: 8, st: 3, ag: 3, pa: 4, av: 9,
        skills: ['Blocage','Arracher le Ballon'],
        normal: ['G','F'], double: ['A','S','M'],
      },
      {
        title: 'Rat-ogre',
        sub: 'Skaven, Gros Bras',
        max: 1, cost: 150,
        ma: 6, st: 5, ag: 4, pa: 6, av: 9,
        skills: ['Sauvagerie Animale','Frénésie','Solitaire (4+)','Châtaigne','Queue Préhensile'],
        normal: ['F'], double: ['A','G','M'],
      },
    ],
  },

  // ============== SNOTLINGS ==============
  snotlings: {
    name: 'Snotlings',
    edition: 'BB2025',
    tier: 3,
    rerollCost: 70,
    apothecary: true,
    league: ['Défi des Bas-Fonds'],
    specialRules: ['Chantage et Corruption','Trois-Quarts à Vil Prix','Déferlement'],
    positions: [
      {
        title: 'Trois-Quart Snotling',
        sub: 'Snotling, Trois-Quart',
        max: 16, cost: 15,
        ma: 5, st: 1, ag: 3, pa: 4, av: 6,
        skills: ['Esquive','Insignifiant','Poids Plume','Glissade Contrôlée','Minus','Microbe'],
        normal: ['A','S'], double: ['G'],
      },
      {
        title: 'R\'bondisseur',
        sub: 'Snotling, Spécial',
        max: 2, cost: 20,
        ma: 6, st: 1, ag: 3, pa: 4, av: 6,
        skills: ['Esquive','Minus','Monté sur Ressort','Poids Plume','Glissade Contrôlée'],
        normal: ['A','S'], double: ['G'],
      },
      {
        title: 'Échassier',
        sub: 'Snotling, Coureur',
        max: 2, cost: 20,
        ma: 6, st: 1, ag: 3, pa: 4, av: 6,
        skills: ['Esquive','Poids Plume','Glissade Contrôlée','Sprint','Minus'],
        normal: ['A','S'], double: ['G'],
      },
      {
        title: 'Lance-champis',
        sub: 'Snotling, Spécial',
        max: 2, cost: 30,
        ma: 5, st: 1, ag: 3, pa: 4, av: 6,
        skills: ['Bombardier','Poids Plume','Esquive','Arme Secrète','Glissade Contrôlée','Minus','Microbe'],
        normal: ['A','S','P'], double: ['G'],
      },
      {
        title: 'Chariot à Pompe',
        sub: 'Snotling, Gros Bras, Spécial',
        max: 2, cost: 100,
        ma: 5, st: 5, ag: 5, pa: 6, av: 9,
        skills: ['Joueur Déloyal','Juggernaut','Châtaigne','Gros Débile','Stabilité'],
        normal: ['S','F'], double: ['A','G'],
      },
      {
        title: 'Troll Entraîné',
        sub: 'Troll, Gros Bras',
        max: 2, cost: 115,
        ma: 4, st: 5, ag: 5, pa: 5, av: 10,
        skills: ['Toujours Affamé','Gerbe de Vomi','Châtaigne','Gros Débile','Régénération','Lancer de Coéquipier'],
        normal: ['F'], double: ['A','G','P'],
      },
    ],
  },

  // ============== UNION ELFIQUE ==============
  union_elfique: {
    name: 'Union Elfique',
    edition: 'BB2025',
    tier: 1,
    rerollCost: 50,
    apothecary: true,
    league: ['Ligue des Royaumes Elfiques'],
    specialRules: [],
    positions: [
      {
        title: 'Trois-Quart Elfe',
        sub: 'Elfe, Trois-Quart',
        max: 16, cost: 65,
        ma: 6, st: 3, ag: 2, pa: 3, av: 8,
        skills: ['Fumblerooski'],
        normal: ['A','G'], double: ['F'],
      },
      {
        title: 'Lanceur Elfe',
        sub: 'Elfe, Lanceur',
        max: 2, cost: 75,
        ma: 6, st: 3, ag: 2, pa: 2, av: 8,
        skills: ['Passe Désespérée','Passe'],
        normal: ['A','G','P'], double: ['F'],
      },
      {
        title: 'Receveur Elfe',
        sub: 'Elfe, Receveur',
        max: 2, cost: 100,
        ma: 8, st: 3, ag: 2, pa: 4, av: 8,
        skills: ['Nerfs d\'Acier','Réception','Réception Plongeante'],
        normal: ['A','G'], double: ['F'],
      },
      {
        title: 'Blitzer Elfe',
        sub: 'Elfe, Blitzer',
        max: 2, cost: 115,
        ma: 7, st: 3, ag: 2, pa: 3, av: 9,
        skills: ['Blocage','Glissade Contrôlée'],
        normal: ['A','G'], double: ['P','F'],
      },
    ],
  },

  // ============== VAMPIRES ==============
  vampires: {
    name: 'Vampires',
    edition: 'BB2025',
    tier: 2,
    rerollCost: 60,
    apothecary: true,
    league: ['Spot de Sylvanie'],
    specialRules: ['Maîtres de la Non-vie'],
    positions: [
      {
        title: 'Trois-Quart Sbire',
        sub: 'Humain, Trois-Quart, Sbire',
        max: 16, cost: 40,
        ma: 6, st: 3, ag: 3, pa: 4, av: 8,
        skills: [],
        normal: ['G'], double: ['A','F'],
      },
      {
        title: 'Coureur Vampire',
        sub: 'Vampire, Coureur, Mort-vivant',
        max: 2, cost: 100,
        ma: 8, st: 3, ag: 2, pa: 3, av: 8,
        skills: ['Soif de Sang (2+)','Regard Hypnotique','Régénération'],
        normal: ['A','G'], double: ['P','F'],
      },
      {
        title: 'Lanceur Vampire',
        sub: 'Vampire, Lanceur, Mort-vivant',
        max: 2, cost: 110,
        ma: 6, st: 4, ag: 2, pa: 2, av: 9,
        skills: ['Soif de Sang (2+)','Regard Hypnotique','Passe','Régénération'],
        normal: ['A','G','P'], double: ['F'],
      },
      {
        title: 'Blitzer Vampire',
        sub: 'Vampire, Blitzer, Mort-vivant',
        max: 2, cost: 110,
        ma: 6, st: 4, ag: 2, pa: 4, av: 9,
        skills: ['Soif de Sang (3+)','Regard Hypnotique','Juggernaut','Régénération'],
        normal: ['A','G','F'], double: [],
      },
      {
        title: 'Vargheist',
        sub: 'Vampire, Gros Bras, Mort-vivant',
        max: 1, cost: 150,
        ma: 5, st: 5, ag: 4, pa: 6, av: 10,
        skills: ['Soif de Sang (3+)','Griffes','Frénésie','Solitaire (4+)','Régénération'],
        normal: ['F'], double: ['A','G'],
      },
    ],
  },

};

// =============================================================
// Sideline Staff (commun)
// =============================================================
const SIDELINE_STAFF = {
  reroll: { label: 'Re-roll', max: 8, useRosterCost: true },
  apothecary: { label: 'Apothicaire', max: 1, cost: 50, requireApothecary: true },
  assistant_coaches: { label: 'Assistants Coach', max: 6, cost: 10 },
  cheerleaders: { label: 'Pom-pom girls', max: 6, cost: 10 },
  dedicated_fans: { label: 'Fans Dévoués', max: 6, cost: 10, min: 1 },
};

// =============================================================
// Catégories de skills BB2025 FR
// =============================================================
const SKILL_CATEGORIES = {
  G: 'Général',
  A: 'Agilité',
  F: 'Force',
  P: 'Passe',
  M: 'Mutation',
  S: 'Scélérates',
};

export { ROSTERS, SIDELINE_STAFF, SKILL_CATEGORIES };
